/*----- PROTECTED REGION ID(FreqDetectorBepClass.h) ENABLED START -----*/
//=============================================================================
//
// file :        FreqDetectorBepClass.h
//
// description : Include for the FreqDetectorBep root class.
//               This class is the singleton class for
//                the FreqDetectorBep device class.
//               It contains all properties and methods which the 
//               FreqDetectorBep requires only once e.g. the commands.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef FreqDetectorBepClass_H
#define FreqDetectorBepClass_H

#include <tango.h>
#include <FreqDetectorBep.h>


/*----- PROTECTED REGION END -----*/	//	FreqDetectorBepClass.h


namespace FreqDetectorBep_ns
{
/*----- PROTECTED REGION ID(FreqDetectorBepClass::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	FreqDetectorBepClass::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute freq class definition
class freqAttrib: public Tango::Attr
{
public:
	freqAttrib():Attr("freq",
			Tango::DEV_FLOAT, Tango::READ_WRITE) {};
	~freqAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<FreqDetectorBep *>(dev))->read_freq(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<FreqDetectorBep *>(dev))->write_freq(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<FreqDetectorBep *>(dev))->is_freq_allowed(ty);}
};


//=========================================
//	Define classes for commands
//=========================================
//	Command OnTimer class definition
class OnTimerClass : public Tango::Command
{
public:
	OnTimerClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	OnTimerClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~OnTimerClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<FreqDetectorBep *>(dev))->is_OnTimer_allowed(any);}
};


/**
 *	The FreqDetectorBepClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  FreqDetectorBepClass : public Tango::DeviceClass
#else
class FreqDetectorBepClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(FreqDetectorBepClass::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	FreqDetectorBepClass::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static FreqDetectorBepClass *init(const char *);
		static FreqDetectorBepClass *instance();
		~FreqDetectorBepClass();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		FreqDetectorBepClass(string &);
		static FreqDetectorBepClass *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	FreqDetectorBep_H
